name: googleapis_generator_dependency

environment:
  sdk: '>=2.0.0-dev.22.0 <3.0.0'

dependencies:
  discoveryapis_generator:
    git: https://github.com/dart-lang/discoveryapis_generator.git
  http: '>=0.11.3+17 <0.13.0'
  node_http: ^1.0.0
  io: ^0.3.3
  pool: ^1.4.0
  yaml: ^2.2.0

